server:
  port: 8090
graphql:
  servlet:
    maxQueryDepth: 20
    actuator-metrics: true
    exception-handlers-enabled: true
  playground:
    enabled: true
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    #cdn:
    #  version: latest